# -*- coding: utf-8 -*-
"""DISAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179b1PQ4lZqYxE41pWvXqemOPddciyIQY
"""

# ==============================================================
# DISASTER RISK MONITORING DASHBOARD
# Author: A'laa Darojah – GIS Engineer
# ==============================================================

import ee
import geemap.foliumap as geemap
import ipywidgets as widgets
from IPython.display import display

# 1. INITIALIZATION
PROJECT_ID = "skripsi-darojah"

def initialize_gee():
    try:
        ee.Initialize(project=PROJECT_ID)
    except Exception:
        ee.Authenticate()
        ee.Initialize(project=PROJECT_ID)

initialize_gee()

# 2. UI COMPONENTS
analysis_selector = widgets.Dropdown(
    options=["Flood Potential (NDWI)", "Vegetation Health (NDVI)", "True Color Satellite"],
    value="Flood Potential (NDWI)",
    description="Layer:"
)

radius_slider = widgets.IntSlider(
    value=10000, min=2000, max=50000, step=2000,
    description="Radius (m):",
    continuous_update=False
)

render_button = widgets.Button(
    description="Update Dashboard",
    button_style="primary",
    icon="refresh"
)

map_output = widgets.Output()

# 3. CLOUD MASKING FUNCTION (Sintaks diperbaiki)
def mask_s2_clouds(image):
    qa = image.select('QA60')
    cloud_bit_mask = 1 << 10
    cirrus_bit_mask = 1 << 11
    # Perbaikan: Menggunakan .And() atau logika bitwise yang tepat
    mask = qa.bitwiseAnd(cloud_bit_mask).eq(0).And(qa.bitwiseAnd(cirrus_bit_mask).eq(0))
    return image.updateMask(mask).divide(10000)

# 4. CORE MAP FUNCTION
def generate_map(event=None):
    with map_output:
        map_output.clear_output()

        center = [-0.96, 116.70]
        point = ee.Geometry.Point(center[1], center[0])
        roi = point.buffer(radius_slider.value).bounds()

        s2_collection = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(roi)
            .filterDate("2024-01-01", "2025-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 30))
            .map(mask_s2_clouds)
        )

        image = s2_collection.median().clip(roi)

        webmap = geemap.Map(center=center, zoom=12)
        webmap.add_basemap("HYBRID")

        if analysis_selector.value == "Flood Potential (NDWI)":
            ndwi = image.normalizedDifference(["B3", "B8"]).rename("NDWI")
            vis = {"min": -0.3, "max": 0.5, "palette": ['#f7f7f7', '#0571b0']}
            webmap.addLayer(ndwi, vis, "Flood Potential (NDWI)")
            webmap.add_colorbar(vis, label="NDWI Index")

        elif analysis_selector.value == "Vegetation Health (NDVI)":
            ndvi = image.normalizedDifference(["B8", "B4"]).rename("NDVI")
            vis = {"min": 0, "max": 0.8, "palette": ['#d73027', '#fdae61', '#1a9850']}
            webmap.addLayer(ndvi, vis, "Vegetation Health (NDVI)")
            webmap.add_colorbar(vis, label="NDVI Index")

        else:
            vis = {"bands": ["B4", "B3", "B2"], "min": 0.0, "max": 0.3}
            webmap.addLayer(image, vis, "True Color Satellite")

        webmap.add_layer_control()
        webmap.to_html("webgis_professional_monitoring.html")
        display(webmap)

# 5. LAYOUT
render_button.on_click(generate_map)
dashboard = widgets.VBox([
    widgets.HTML("<h2>🛡️ Disaster Risk Dashboard</h2>"),
    widgets.HBox([analysis_selector, radius_slider, render_button]),
    map_output
])

display(dashboard)
generate_map()